### ISSUE TITLE
Expected behaviour for template containing text like #{$Foo}?

### ISSUE THREAD

**Issue by jasonmitchell** [OctopusDeploy/Octostache#5]
I encountered an issue when transforming a file in Octopus Deploy where a piece of text in the file in the format of #{$Foo} caused the error:

> Parsing failure: unexpected '#'; expected end of input (Line 1, Column 1); recently consumed: 

I am not trying to substitute this piece of text it just happens to be in file being transformed. I've added a test case as an example:

https://github.com/jasonmitchell/Octostache/commit/018e6c609cc5f4f5e082215b4039d15a448faf74

The error message for this test is the same as the other cases for the test.  I wanted to clarify if this is expected behaviour or is a bug in the template parser?

If this is expected is there anyway to work around other than removing the piece of text from the file?

**Comment by mattsalmon** [comment]
I've also had this same issue - surprised there's nobody else encountered this scenario!

**Comment by gurufordy** [comment]
I also get this issue when running the DACPAC deploy community library script as below

[https://library.octopusdeploy.com/step-template/actiontemplate-sql-deploy-dacpac](url)

It has the following code:

`Function Format-OctopusArgument {

	Param(
		[string]$Value
	)

	$Value = $Value.Trim()

	# There must be a better way to do this
	Switch -Wildcard ($Value){

		"True" { Return $True }
		"False" { Return $False }
		"#{*}" { Return $null }
		Default { Return $Value }
	}
}`

**Comment by zentron** [comment]
Hi guys, this issue is because Octostache sees `#{` and thinks you are asking for a variable replacement. To avoid this issue, add another `#` before it (e.g. `"##{*}" { Return $null }`) and when variable replacement takes place, Octostache will remove the extra `#` leaving you with the value you are after.
I have updated [our docs](http://docs.octopusdeploy.com/display/OD/Variable+Substitution+Syntax) outlining this behaviour. 
I hope that helps!
