### ISSUE TITLE
Allow variables to be saved to other formats/persistence stores

### ISSUE THREAD

**Issue by SeanFarrow** [OctopusDeploy/Octostache#8]
Hi,

It would be nice if Octostache allowed variables to be persisted in other formats than json and to other stores other than just a regular file.

To my mind this would mean extracting the serialization and formatting logic out of variable dictionary, behind an interface.

I am happy to work on this if this would be something that would be useful.
Cheers
sean.

**Comment by zentron** [comment]
Hi @SeanFarrow , I can understand that you may have other formats you would like to use out of curiosity whats the scenario you are trying to support?
Being open source, with a relatively permissive licence (Apache) we are more than happy for you to fork this  repository and tweak to your heart's content.
Since we use this library in Octopus Deploy and would like to keep its complexity to a minimum, I can't guarantee it will be merged into the `Octostache` mainline but I would still be interested to see where you take it.

**Comment by SeanFarrow** [comment]
Hi,

Given we’re in a cloud environment, saving to files doesn’t work, so we need to support an alternative store.
I’m thinking of either supporting a database or upload to either s3 or azure blob storage.
I would think this would be something you would be interested in. Potentially splitting the storage in to a repository.
Cheers
Sean.
